  name: ambush_app
  description: The easy way to create and manage invoices on your mobile device.

  publish_to: 'none' # Remove this line if you wish to publish to pub.dev
  version: 0.4.3+18

  environment:
    sdk: '>=3.4.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.6
    intl: ^0.19.0
    flutter_mobx: ^2.2.0+2
    mobx: ^2.3.0+1
    get_it: ^8.0.0
    injectable: ^2.4.0
    dynamic_color: ^1.6.6
    auto_route: ^9.0.0
    pdf: ^3.10.8
    path_provider: ^2.1.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    share_plus: ^10.0.0
    image: ^4.1.7 # fix for the PDF package test_api 0.5.1 (0.6.1 available)
    flutter_svg: ^2.0.10+1
    flutter_svg_provider: ^1.0.7
    universal_html: ^2.2.4
    material_color_utilities: ^0.11.1
    file_picker: ^8.0.3
    extended_masked_text: ^3.0.1

  dev_dependencies:
    flutter_test:
      sdk: flutter

    flutter_lints: ^5.0.0
    build_runner: ^2.4.11
    mobx_codegen: ^2.3.0
    injectable_generator: ^2.1.5
    auto_route_generator: ^9.0.0
    hive_generator: ^2.0.0
    test: ^1.25.2

  flutter:
    uses-material-design: true
    fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/poppins/Poppins-Thin.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
            weight: 200
            style: italic
          - asset: assets/fonts/poppins/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/poppins/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/poppins/Poppins-Italic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/poppins/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/poppins/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          - asset: assets/fonts/poppins/Poppins-Black.ttf
            weight: 900
          - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
            weight: 900
            style: italic
      - family: Mundial
        fonts:
          - asset: assets/fonts/mundial/mundial-thin-tty.otf
            weight: 100
          - asset: assets/fonts/mundial/mundial-thin-italic-tty.otf
            weight: 100
            style: italic
          - asset: assets/fonts/mundial/mundial-light-tty.otf
            weight: 300
          - asset: assets/fonts/mundial/mundial-light-italic-tty.otf
            weight: 300
            style: italic
          - asset: assets/fonts/mundial/mundial-regular-tty.otf
            weight: 400
          - asset: assets/fonts/mundial/mundial-regular-italic-tty.otf
            weight: 400
            style: italic
          - asset: assets/fonts/mundial/mundial-demibold-tty.otf
            weight: 600
          - asset: assets/fonts/mundial/mundial-demibold-italic-tty.otf
            weight: 600
            style: italic
          - asset: assets/fonts/mundial/mundial-bold-tty.otf
            weight: 700
          - asset: assets/fonts/mundial/mundial-bold-italic-tty.otf
            weight: 700
            style: italic
          - asset: assets/fonts/mundial/mundial-black-tty.otf
            weight: 900
          - asset: assets/fonts/mundial/mundial-black-italic-tty.otf
            weight: 900
            style: italic

    assets:
      - assets/extended_logo.svg
      - assets/currency.json
      - assets/icons/
      - assets/illustration_success.png

  #Font mapping -------------------
  #FontWeight.w100: 'Thin',
  #FontWeight.w200: 'ExtraLight',
  #FontWeight.w300: 'Light',
  #FontWeight.w400: 'Regular',
  #FontWeight.w500: 'Medium',
  #FontWeight.w600: 'SemiBold',
  #FontWeight.w700: 'Bold',
  #FontWeight.w800: 'ExtraBold',
  #FontWeight.w900: 'Black',
